#!/usr/bin/env python3
"""Validate the GitHub mining project against the grading rubric."""
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw" / "github_repos.json"
PROCESSED = ROOT / "data" / "processed"
APP = ROOT / "app"
NOTEBOOK = ROOT / "github_mining_analysis.ipynb"
REPORT = ROOT / "outputs" / "project_report.md"
PRESENTATION = ROOT / "outputs" / "presentation_outline.md"


def load_json(path: Path):
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def check(condition: bool, label: str, detail: str, score: int, max_score: int) -> dict:
    return {
        "item": label,
        "status": "PASS" if condition else "FAIL",
        "score": score if condition else 0,
        "max_score": max_score,
        "detail": detail,
    }


def main() -> None:
    required = [
        RAW,
        PROCESSED / "stats.json",
        PROCESSED / "repos.json",
        PROCESSED / "graph_nodes.json",
        PROCESSED / "graph_edges.json",
        PROCESSED / "association_rules.json",
        PROCESSED / "similarities.json",
    ]
    missing = [str(path.relative_to(ROOT)) for path in required if not path.exists()]
    if missing:
        raise SystemExit("Missing required files: " + ", ".join(missing))

    raw = load_json(RAW)
    stats = load_json(PROCESSED / "stats.json")
    repos = load_json(PROCESSED / "repos.json")
    nodes = load_json(PROCESSED / "graph_nodes.json")
    edges = load_json(PROCESSED / "graph_edges.json")
    rules = load_json(PROCESSED / "association_rules.json")
    similarities = load_json(PROCESSED / "similarities.json")

    origins = stats.get("data_source_distribution", {})
    real_count = origins.get("github_api", 0)
    required_repo_columns = {
        "name", "stars", "forks", "language", "topics", "description",
        "tech_stack", "bert_category", "bert_confidence", "cluster_id",
        "pca_x", "pca_y", "html_url",
    }
    repo_columns = set(repos[0]) if repos else set()

    checks = [
        check(
            real_count > 0 and len(raw) == len(repos) == stats["total_repos"],
            "Data Collection & Understanding",
            f"{real_count:,} real GitHub API repositories; raw/repos/stats counts match.",
            2,
            2,
        ),
        check(
            required_repo_columns.issubset(repo_columns)
            and all(repo.get("tech_stack") for repo in repos[: min(200, len(repos))]),
            "Data Preprocessing",
            "Cleaned schema, normalized tech_stack, semantic labels, PCA coordinates.",
            2,
            2,
        ),
        check(
            len(rules) >= 100
            and {"support", "confidence", "lift", "conviction", "leverage"}.issubset(set(rules[0])),
            "Association Rule Mining",
            f"{len(rules):,} Apriori rules with support/confidence/lift/conviction/leverage.",
            2,
            2,
        ),
        check(
            len(nodes) >= 20
            and len(edges) >= 100
            and {"pagerank", "hub", "authority", "community"}.issubset(set(nodes[0])),
            "Link Analysis (PageRank/HITS)",
            f"{len(nodes):,} graph nodes, {len(edges):,} edges, PageRank, HITS, communities.",
            2,
            2,
        ),
        check(
            (APP / "index.html").exists()
            and (APP / "js" / "app.js").exists()
            and (APP / "css" / "styles.css").exists()
            and NOTEBOOK.exists(),
            "Visualization",
            "Notebook plots plus interactive HTML/CSS/JS dashboard GUI.",
            1,
            1,
        ),
        check(
            REPORT.exists() and PRESENTATION.exists(),
            "Report & Presentation",
            "Markdown report and presentation outline generated by the pipeline.",
            1,
            1,
        ),
        check(
            "embedding_method" in stats
            and stats.get("total_categories", 0) >= 5
            and len(similarities) == len(repos),
            "BERT / Semantic Analysis",
            f"{stats.get('embedding_method')} with {stats.get('total_categories')} categories and similarity index.",
            5,
            5,
        ),
    ]

    total = sum(item["score"] for item in checks)
    max_total = sum(item["max_score"] for item in checks)
    report_lines = [
        "# Project Validation Report",
        "",
        f"Score: {total}/{max_total}",
        "",
        "| Item | Status | Score | Evidence |",
        "|---|---|---:|---|",
    ]
    for item in checks:
        report_lines.append(
            f"| {item['item']} | {item['status']} | {item['score']}/{item['max_score']} | {item['detail']} |"
        )

    report_lines.extend([
        "",
        "## Dataset Snapshot",
        "",
        f"- Data source distribution: {origins}",
        f"- Repositories: {stats['total_repos']:,}",
        f"- Technologies/topics: {stats['total_technologies']:,}",
        f"- Graph edges: {stats['total_edges']:,}",
        f"- Association rules: {len(rules):,}",
        f"- Semantic categories: {stats['total_categories']:,}",
    ])

    output = ROOT / "outputs" / "validation_report.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(report_lines) + "\n", encoding="utf-8")

    print(f"Validation score: {total}/{max_total}")
    for item in checks:
        print(f"[{item['status']}] {item['item']}: {item['score']}/{item['max_score']} - {item['detail']}")
    print(f"Report written to: {output}")

    if any(item["status"] != "PASS" for item in checks):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
